{"@t":"2021-09-02T04:50:30.5267706Z","@mt":"Acquiring.","SourceContext":"Umbraco.Cms.Core.Runtime.MainDom","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T04:50:30.5626559Z","@mt":"Acquired.","SourceContext":"Umbraco.Cms.Core.Runtime.MainDom","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T04:50:42.0322657Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:6b6a5c46-e72f-487f-8403-e14138f6ee62\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T04:50:43.2092948Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:6b6a5c46-e72f-487f-8403-e14138f6ee62\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T04:50:44.5767929Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:6b6a5c46-e72f-487f-8403-e14138f6ee62\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T04:50:45.7567239Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:6b6a5c46-e72f-487f-8403-e14138f6ee62\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T04:50:57.3503449Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:3636f0ce-025a-4be1-a6cd-f2e71aa81058\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T04:50:57.3768053Z","@mt":"Boot Failed","@l":"Error","@x":"Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\r\n   at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()","SourceContext":"Umbraco.Cms.Infrastructure.Runtime.CoreRuntime","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"ERROR"}
{"@t":"2021-09-02T04:50:58.7500734Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T04:50:58.7506921Z","@mt":"Hosting environment: {envName}","envName":"Development","SourceContext":"Microsoft.Hosting.Lifetime","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T04:50:58.7515132Z","@mt":"Content root path: {contentRoot}","contentRoot":"C:\\Users\\apurv\\Desktop\\ASP.NET\\MyUmbracoProject","SourceContext":"Microsoft.Hosting.Lifetime","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T04:50:58.9771209Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.\n\n-> Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\n   at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)\r\n   at Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"80000028-0006-f000-b63f-84710c7967bb","RequestPath":"/","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"ERROR"}
{"@t":"2021-09-02T04:50:59.5965886Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.\n\n-> Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\n   at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)\r\n   at Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"800001d7-0007-f800-b63f-84710c7967bb","RequestPath":"/favicon.ico","ProcessId":17372,"ProcessName":"iisexpress","ThreadId":5,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"ERROR"}
{"@t":"2021-09-02T05:27:25.1274263Z","@mt":"Acquiring.","SourceContext":"Umbraco.Cms.Core.Runtime.MainDom","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:27:25.1646690Z","@mt":"Acquired.","SourceContext":"Umbraco.Cms.Core.Runtime.MainDom","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:27:36.4756685Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:6a5de070-f437-4aa8-836b-c249bf0fe10c\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T05:27:37.6399758Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:6a5de070-f437-4aa8-836b-c249bf0fe10c\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T05:27:38.8091754Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:6a5de070-f437-4aa8-836b-c249bf0fe10c\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T05:27:39.9870055Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:6a5de070-f437-4aa8-836b-c249bf0fe10c\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T05:27:41.1634274Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"umbraco-db-test\" requested by the login. The login failed.\r\nLogin failed for user 'LAPTOP-KG89FUQC\\apurv'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Extensions.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:6a5de070-f437-4aa8-836b-c249bf0fe10c\r\nError Number:4060,State:1,Class:11","SourceContext":"object","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"WARN "}
{"@t":"2021-09-02T05:27:41.2208253Z","@mt":"Boot Failed","@l":"Error","@x":"Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\r\n   at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()","SourceContext":"Umbraco.Cms.Infrastructure.Runtime.CoreRuntime","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"ERROR"}
{"@t":"2021-09-02T05:27:43.1227159Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:27:43.1231441Z","@mt":"Hosting environment: {envName}","envName":"Development","SourceContext":"Microsoft.Hosting.Lifetime","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:27:43.1241660Z","@mt":"Content root path: {contentRoot}","contentRoot":"C:\\Users\\apurv\\Desktop\\ASP.NET\\MyUmbracoProject","SourceContext":"Microsoft.Hosting.Lifetime","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:27:43.6760714Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.\n\n-> Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\n   at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)\r\n   at Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"8000019b-0005-fd00-b63f-84710c7967bb","RequestPath":"/","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"ERROR"}
{"@t":"2021-09-02T05:27:43.6760714Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.\n\n-> Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\n   at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)\r\n   at Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"8000007e-0002-e900-b63f-84710c7967bb","RequestPath":"/umbraco","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":5,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"ERROR"}
{"@t":"2021-09-02T05:27:43.6760714Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.\n\n-> Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\n   at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)\r\n   at Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"8000017b-0005-ff00-b63f-84710c7967bb","RequestPath":"/umbraco","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":4,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"ERROR"}
{"@t":"2021-09-02T05:27:44.4851846Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.\n\n-> Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\n   at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)\r\n   at Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"8000016e-0001-ed00-b63f-84710c7967bb","RequestPath":"/favicon.ico","ProcessId":15632,"ProcessName":"iisexpress","ThreadId":14,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"ERROR"}
{"@t":"2021-09-02T05:29:13.0051889Z","@mt":"Acquiring.","SourceContext":"Umbraco.Cms.Core.Runtime.MainDom","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:29:13.0402892Z","@mt":"Acquired.","SourceContext":"Umbraco.Cms.Core.Runtime.MainDom","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:29:17.8784549Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:29:17.8788938Z","@mt":"Hosting environment: {envName}","envName":"Development","SourceContext":"Microsoft.Hosting.Lifetime","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:29:17.8793813Z","@mt":"Content root path: {contentRoot}","contentRoot":"C:\\Users\\apurv\\Desktop\\ASP.NET\\MyUmbracoProject","SourceContext":"Microsoft.Hosting.Lifetime","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO "}
{"@t":"2021-09-02T05:29:18.7141621Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService","RequestId":"8000024f-0002-ea00-b63f-84710c7967bb","RequestPath":"/","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":4,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO ","HttpRequestId":"eeffdd72-496f-4bbf-9886-75a5264f6419","HttpRequestNumber":1,"HttpSessionId":"0"}
{"@t":"2021-09-02T05:29:18.7188523Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService","RequestId":"8000024f-0002-ea00-b63f-84710c7967bb","RequestPath":"/","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":4,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO ","HttpRequestId":"eeffdd72-496f-4bbf-9886-75a5264f6419","HttpRequestNumber":1,"HttpSessionId":"0"}
{"@t":"2021-09-02T05:29:18.7243101Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService","RequestId":"8000024f-0002-ea00-b63f-84710c7967bb","RequestPath":"/","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":4,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO ","HttpRequestId":"eeffdd72-496f-4bbf-9886-75a5264f6419","HttpRequestNumber":1,"HttpSessionId":"0"}
{"@t":"2021-09-02T05:29:20.5650881Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from local cache file","TimingId":"9a914e9","SourceContext":"Umbraco.Cms.Core.Logging.ProfilingLogger","RequestId":"8000024f-0002-ea00-b63f-84710c7967bb","RequestPath":"/","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":4,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO ","HttpRequestId":"eeffdd72-496f-4bbf-9886-75a5264f6419","HttpRequestNumber":1,"HttpSessionId":"0"}
{"@t":"2021-09-02T05:29:20.6468967Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":82,"TimingId":"9a914e9","SourceContext":"Umbraco.Cms.Core.Logging.ProfilingLogger","RequestId":"8000024f-0002-ea00-b63f-84710c7967bb","RequestPath":"/","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":4,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO ","HttpRequestId":"eeffdd72-496f-4bbf-9886-75a5264f6419","HttpRequestNumber":1,"HttpSessionId":"0"}
{"@t":"2021-09-02T05:29:20.6708119Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from local cache file","TimingId":"6a71d8a","SourceContext":"Umbraco.Cms.Core.Logging.ProfilingLogger","RequestId":"8000024f-0002-ea00-b63f-84710c7967bb","RequestPath":"/","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":4,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO ","HttpRequestId":"eeffdd72-496f-4bbf-9886-75a5264f6419","HttpRequestNumber":1,"HttpSessionId":"0"}
{"@t":"2021-09-02T05:29:20.6720100Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":1,"TimingId":"6a71d8a","SourceContext":"Umbraco.Cms.Core.Logging.ProfilingLogger","RequestId":"8000024f-0002-ea00-b63f-84710c7967bb","RequestPath":"/","ProcessId":15664,"ProcessName":"iisexpress","ThreadId":4,"AppDomainId":1,"AppDomainAppId":"3fa43537f8d716c6931bdd658c0e8840c2742ea0","MachineName":"LAPTOP-KG89FUQC","Log4NetLevel":"INFO ","HttpRequestId":"eeffdd72-496f-4bbf-9886-75a5264f6419","HttpRequestNumber":1,"HttpSessionId":"0"}
